# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bbdbf48e76d2de35336589bdcce8d60c1b245a726bd448e3ce105b93370006eefa5f84d00676995c160b5a3012b38ffdf0c1036cc09228c8d266ec955c42336

test:
  secret_key_base: 158f8bed0c1b2613bddadb440f8aac99a70862787927e370a6740f6e324889245fa3a2553f607363dba60648ce97d3d7392843353cae56a506d691c4a93c715b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
